WIFI_SSID = "SSID_Name"
WIFI_PASSWORD = "Password123"

NTP_SERVER = "NTP_SERVER"

MQTT_SERVER_IP = "MQTT_SERVER_IP"
MQTT_SERVER_PORT = 1883
MQTT_SERVER_USER = "MQTT_USER"
MQTT_SERVER_PASSWORD = "MQTT_PASSWORD"
